version: '{branch}-{build}'

os: Visual Studio 2015

environment:
  DNX_FEED: https://www.nuget.org/api/v2
  DNX_BUILD_VERSION: build$(appveyor_build_number)

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

branches:
  only:
    - master

skip_tags: true

skip_commits:
  message: /\<\.nobuild\>

init:
  - ps: dnvm install latest

shallow_clone: true

clone_depth: 1

install:
  - ps: $env:SRC_DIR = (get-content .src)
  - ps: dnu restore $env:SRC_DIR

build_script:
  - ps: dnu pack --configuration Release $env:SRC_DIR

artifacts:
  - path: '**\*.nupkg'

notifications:
  - provider: Email
    to: jedahu@gmail.com
    on_build_status_changed: true
